/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import conexao.Conexao;
import dao.CandidatoDAO;
import dao.EleitorDAO;
import dao.PartidoDAO;
import dao.VotoDAO;
import dao.UrnaDAO;
import java.awt.Color;
import java.awt.Cursor;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.CadCandidato;
import modelo.CadEleitor;
import modelo.Voto;

/**
 *
 * @author paulohx
 */
public class Urna extends javax.swing.JFrame {
    
    CandidatoDAO candidatoDAO = new CandidatoDAO();
    PartidoDAO   partidoDAO   = new PartidoDAO();
    VotoDAO      votoDAO      = new VotoDAO();
    UrnaDAO      urna         = new UrnaDAO();
    EleitorDAO   eleitorDAO   = new EleitorDAO();
    
    CadEleitor eleitor = null;
    CadCandidato candidatoVoto = null;
    
    Voto votoContabilizar = null;
    
    CadCandidato candidatos[] = candidatoDAO.getVetorCandidato();
    Voto voto[] = votoDAO.getVetorVoto();
    CadEleitor eleitores[]  ;//  = eleitorDAO.getVetorEleitor();
    boolean primeiroDigito;
    
    /**
     * Creates new form UrnaDAO
     * @throws java.io.IOException
     */
    public Urna(CadEleitor eleitor, UrnaDAO urna, EleitorDAO eleitorDAO){
                
        initComponents();
        this.eleitor = eleitor;
        this.votoContabilizar = new Voto(urna);
        this.eleitorDAO = eleitorDAO;
        this.eleitores = this.eleitorDAO.getVetorEleitor();
        primeiroDigito = false;
        this.requestFocus();
        this.getContentPane().setBackground(new java.awt.Color(245,245,245));
        this.setLocationRelativeTo(null);
        this.setExtendedState(HIDE_ON_CLOSE);
        iniciaCores();
    
        try {
            partidoDAO.baixarPartidoJson();
        } catch (IOException ex) {
            Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            candidatoDAO.baixarCandidatoJson();
        } catch (IOException ex) {
            Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    
    private void iniciaCores(){
        
        this.panelIcone.setBackground(new java.awt.Color(245,245,245));
        this.setBackground(new java.awt.Color(0,0,0));
        btnConfirma.setBackground(new java.awt.Color(0,100,0));
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });
        btnCorrige.setBackground(new java.awt.Color(255,140,0));
        btnCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrigeActionPerformed(evt);
            }
        });
        
        btnNum0.setForeground(Color.WHITE);
        btnNum0.setBackground(Color.BLACK);
        
        btnNum1.setForeground(Color.WHITE);
        btnNum1.setBackground(Color.BLACK);
        
        btnNum2.setForeground(Color.WHITE);
        btnNum2.setBackground(Color.BLACK);
        
        btnNum3.setForeground(Color.WHITE);
        btnNum3.setBackground(Color.BLACK);
        
        btnNum4.setForeground(Color.WHITE);
        btnNum4.setBackground(Color.BLACK);
        
        btnNum5.setForeground(Color.WHITE);
        btnNum5.setBackground(Color.BLACK);
        
        btnNum6.setForeground(Color.WHITE);
        btnNum6.setBackground(Color.BLACK);
        
        btnNum7.setForeground(Color.WHITE);
        btnNum7.setBackground(Color.BLACK);
        
        btnNum8.setForeground(Color.WHITE);
        btnNum8.setBackground(Color.BLACK);
        
        btnNum9.setForeground(Color.WHITE);
        btnNum9.setBackground(Color.BLACK);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        btnConfirma = new javax.swing.JButton();
        btnBranco = new javax.swing.JButton();
        btnCorrige = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        texSegundoDigito = new java.awt.TextField();
        texPrimeiroDigito = new java.awt.TextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        lblCandidatoNome = new java.awt.Label();
        lblCandidatoPartido = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelIcone = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(930, 570));
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(14, 7, 7));

        btnConfirma.setFont(new java.awt.Font("Chandas", 1, 10)); // NOI18N
        btnConfirma.setText("CONFIRMA");
        btnConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmaMouseEntered(evt);
            }
        });
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });
        btnConfirma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmaKeyPressed(evt);
            }
        });

        btnBranco.setFont(new java.awt.Font("Chandas", 1, 10)); // NOI18N
        btnBranco.setText("BRANCO");
        btnBranco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBrancoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBrancoMouseEntered(evt);
            }
        });
        btnBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrancoActionPerformed(evt);
            }
        });

        btnCorrige.setFont(new java.awt.Font("Chandas", 1, 10)); // NOI18N
        btnCorrige.setText("CORRIGE");
        btnCorrige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCorrigeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCorrigeMouseEntered(evt);
            }
        });
        btnCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrigeActionPerformed(evt);
            }
        });

        btnNum2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum2.setText("2");
        btnNum2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum2MouseEntered(evt);
            }
        });
        btnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum2ActionPerformed(evt);
            }
        });

        btnNum4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum4.setText("4");
        btnNum4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum4MouseEntered(evt);
            }
        });
        btnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum4ActionPerformed(evt);
            }
        });

        btnNum7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum7.setText("7");
        btnNum7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum7MouseEntered(evt);
            }
        });
        btnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum7ActionPerformed(evt);
            }
        });

        btnNum5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum5.setText("5");
        btnNum5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum5MouseEntered(evt);
            }
        });
        btnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum5ActionPerformed(evt);
            }
        });

        btnNum6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum6.setText("6");
        btnNum6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum6MouseEntered(evt);
            }
        });
        btnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum6ActionPerformed(evt);
            }
        });

        btnNum8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum8.setText("8");
        btnNum8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum8MouseEntered(evt);
            }
        });
        btnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum8ActionPerformed(evt);
            }
        });

        btnNum9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum9.setText("9");
        btnNum9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum9MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum9MouseEntered(evt);
            }
        });
        btnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum9ActionPerformed(evt);
            }
        });

        btnNum1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum1.setText("1");
        btnNum1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum1MouseEntered(evt);
            }
        });
        btnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum1ActionPerformed(evt);
            }
        });

        btnNum3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum3.setText("3");
        btnNum3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum3MouseEntered(evt);
            }
        });
        btnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum3ActionPerformed(evt);
            }
        });

        btnNum0.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnNum0.setText("0");
        btnNum0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum0MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum0MouseEntered(evt);
            }
        });
        btnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBranco, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNum7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(btnNum4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNum9, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(btnNum6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(32, 32, 32))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        getContentPane().add(panel1);
        panel1.setBounds(556, 73, 336, 431);

        panel3.setBackground(new java.awt.Color(122, 113, 113));

        panel2.setBackground(new java.awt.Color(254, 254, 254));

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Aperte a tecla:");

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("VERDE para CONFIRMAR o voto");

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("LARANJA para CORRIGIR o voto");

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("BRANCO para ANULAR o voto");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        texSegundoDigito.setEditable(false);
        texSegundoDigito.setEnabled(false);
        texSegundoDigito.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N

        texPrimeiroDigito.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        texPrimeiroDigito.setEditable(false);
        texPrimeiroDigito.setEnabled(false);
        texPrimeiroDigito.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText("SEU VOTO PARA");

        label6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label6.setText("PRESIDENTE");

        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setText("Número:");

        label8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label8.setText("Partido:");

        label9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label9.setText("Nome:");

        lblCandidatoNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblCandidatoPartido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCandidatoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCandidatoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(texPrimeiroDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texSegundoDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE))))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(texSegundoDigito, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(texPrimeiroDigito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCandidatoNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCandidatoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panel3);
        panel3.setBounds(21, 55, 510, 500);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jLabel1.setText("JUSTIÇA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(785, 0, 107, 31);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jLabel3.setText("ELEITORAL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(749, 32, 143, 31);

        panelIcone.setBackground(new java.awt.Color(254, 254, 254));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/paulohx/NetBeansProjects/Urna/src/main/resources/logotipo-miniatura.png")); // NOI18N

        javax.swing.GroupLayout panelIconeLayout = new javax.swing.GroupLayout(panelIcone);
        panelIcone.setLayout(panelIconeLayout);
        panelIconeLayout.setHorizontalGroup(
            panelIconeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconeLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        panelIconeLayout.setVerticalGroup(
            panelIconeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconeLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelIcone);
        panelIcone.setBounds(595, 10, 81, 53);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private CadCandidato verificandoCandidato(){
        int aux1 = Character.getNumericValue(texPrimeiroDigito.getText().charAt(2)); 
        int aux2 = Character.getNumericValue(texSegundoDigito.getText().charAt(2)); 
        String aux;
        aux  = Integer.toString(aux1);
        aux += Integer.toString(aux2);
        
        candidatoVoto = candidatoDAO.getCandidatoByNum(Integer.parseInt(aux));
        if(candidatoVoto != null){
            lblCandidatoNome.setText(candidatoVoto.getNome());
            lblCandidatoPartido.setText(candidatoVoto.getPartido().getNome());
            return(candidatoVoto);
        }else{
            lblCandidatoNome.setText("Candidato Inválido");
            return(candidatoVoto);
        }        
    }
    
    private void controleBotoes(boolean controle){

        btnNum0.setEnabled(controle);
        btnNum1.setEnabled(controle);
        btnNum2.setEnabled(controle);
        btnNum3.setEnabled(controle);
        btnNum4.setEnabled(controle);
        btnNum5.setEnabled(controle);
        btnNum6.setEnabled(controle);
        btnNum7.setEnabled(controle);
        btnNum8.setEnabled(controle);
        btnNum9.setEnabled(controle);
        
    }
    
    private void desabilitandoTelaUrna(){
        
            label1.setVisible(false);
            label2.setVisible(false);
            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            label6.setVisible(false);
            label7.setVisible(false);
            label8.setVisible(false);
            label9.setVisible(false);
            texPrimeiroDigito.setVisible(false);
            texSegundoDigito.setVisible(false);
            lblCandidatoNome.setVisible(false);
            lblCandidatoPartido.setVisible(false);
    }
    
    private void btnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum1ActionPerformed
        
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  1");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  1");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();
        }
    }//GEN-LAST:event_btnNum1ActionPerformed

    private void btnCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrigeActionPerformed
        controleBotoes(true);
        texPrimeiroDigito.setText("");
        texSegundoDigito.setText("");
        lblCandidatoNome.setText("");
        lblCandidatoPartido.setText("");
        primeiroDigito = false;
    }//GEN-LAST:event_btnCorrigeActionPerformed

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void btnConfirmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmaMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnConfirmaMouseEntered

    private void btnCorrigeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorrigeMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCorrigeMouseEntered

    private void btnBrancoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrancoMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnBrancoMouseEntered

    private void btnNum0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum0MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum0MouseEntered

    private void btnNum9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum9MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum9MouseEntered

    private void btnNum8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum8MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum8MouseEntered

    private void btnNum7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum7MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum7MouseEntered

    private void btnNum6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum6MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum6MouseEntered

    private void btnNum5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum5MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum5MouseEntered

    private void btnNum4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum4MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum4MouseEntered

    private void btnNum3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum3MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum3MouseEntered

    private void btnNum2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum2MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum2MouseEntered

    private void btnNum1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum1MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNum1MouseEntered

    private void btnBrancoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrancoMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnBrancoMouseExited

    private void btnCorrigeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorrigeMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnCorrigeMouseExited

    private void btnConfirmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmaMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnConfirmaMouseExited

    private void btnNum0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum0MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum0MouseExited

    private void btnNum9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum9MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum9MouseExited

    private void btnNum8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum8MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum8MouseExited

    private void btnNum7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum7MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum7MouseExited

    private void btnNum1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum1MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum1MouseExited

    private void btnNum2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum2MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));                
    }//GEN-LAST:event_btnNum2MouseExited

    private void btnNum3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum3MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum3MouseExited

    private void btnNum4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum4MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum4MouseExited

    private void btnNum5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum5MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum5MouseExited

    private void btnNum6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum6MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNum6MouseExited

    private void btnConfirmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmaKeyPressed
//        this.dispose();
    }//GEN-LAST:event_btnConfirmaKeyPressed

    private void btnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum2ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  2");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  2");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();
        }
    }//GEN-LAST:event_btnNum2ActionPerformed

    private void btnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum3ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  3");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  3");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();
        }
    }//GEN-LAST:event_btnNum3ActionPerformed

    private void btnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum4ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  4");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  4");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();
        }
    }//GEN-LAST:event_btnNum4ActionPerformed

    private void btnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum5ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  5");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  5");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();
        }    
    }//GEN-LAST:event_btnNum5ActionPerformed

    private void btnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum6ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  6");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  6");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();            
        }
    }//GEN-LAST:event_btnNum6ActionPerformed

    private void btnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum7ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  7");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  7");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();
        }
    }//GEN-LAST:event_btnNum7ActionPerformed

    private void btnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum8ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  8");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  8");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();
        }
    }//GEN-LAST:event_btnNum8ActionPerformed

    private void btnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum9ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  9");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  9");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();            
        }
    }//GEN-LAST:event_btnNum9ActionPerformed

    private void btnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum0ActionPerformed
        if(!primeiroDigito){
            texPrimeiroDigito.setText("  0");
            primeiroDigito = true;
        }else{
            texSegundoDigito.setText("  0");
            controleBotoes(false);
            candidatoVoto = verificandoCandidato();
        }
    }//GEN-LAST:event_btnNum0ActionPerformed

    private void btnBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrancoActionPerformed
        lblCandidatoNome.setText("VOTO NULO");
        lblCandidatoPartido.setText("");
//        eleitor.setVotou(true);
        this.dispose();
    }//GEN-LAST:event_btnBrancoActionPerformed

    private void btnConfirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmaMouseClicked

        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        if(candidatoVoto != null){
            for(int i = 0; i < candidatos.length; ++i ){
                if(candidatos[i] != null){
                    if(candidatoVoto.getNumero() == candidatos[i].getNumero()){
                        candidatos[i].setQtdeVoto(1);
                        eleitor.setVotou(true);
                        break;
                    }
                }
            }
            
            //Criando um arquivo para atualizar os dados do driver
            FileWriter arq = null;
            try {
                arq = new FileWriter("./ArquivosJson/Candidato.json");
                arq.close();
            } catch (IOException ex) {
                Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            arq = null;
            try {
                arq = new FileWriter("./ArquivosJson/Eleitor.json");
                arq.close();
            } catch (IOException ex) {
                Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            for(int i =0; i < candidatos.length; i++){
                if(candidatos[i] != null){
                    candidatoDAO.inserirJson(candidatos[i]);
                }
            }
            
            for(int i =0; i < eleitores.length; i++){
                if(eleitores[i] != null){
                    eleitorDAO.inserirJson(eleitores[i]);
                }
            }
            
            desabilitandoTelaUrna();
            
            votoContabilizar.setCpfEleitor(eleitor.getCpf());
            votoContabilizar.setCandidato(candidatoVoto);
            
            votoDAO.inserir(votoContabilizar);
            votoDAO.inserirJson(votoContabilizar);
            
            
            eleitorDAO.enviaDrive();
            candidatoDAO.enviaDrive();
            votoDAO.enviaDrive();
            
            this.dispose();
        }
        
    }//GEN-LAST:event_btnConfirmaMouseClicked
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBranco;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnCorrige;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label lblCandidatoNome;
    private java.awt.Label lblCandidatoPartido;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panelIcone;
    private java.awt.TextField texPrimeiroDigito;
    private java.awt.TextField texSegundoDigito;
    // End of variables declaration//GEN-END:variables
}
